# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with Sphinx
sphinx:
  builder: html
  configuration: python/doc/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: python/requirements.txt
    - method: setuptools
      path: python/doc
    - method: setuptools
      path: python
  system_packages: true
